FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app:/app

WORKDIR /app

COPY ./alembic/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN rm /app/requirements.txt

COPY app/models /app/models

COPY app/core/config.py /app/core/config.py
COPY ./alembic ./alembic

RUN rm /app/alembic/requirements.*
COPY alembic.ini .


CMD ["echo", "WARNING, RUN THIS DOCKERFILE IN DOCKER-COMPOSE"]