FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app:/app/app

WORKDIR /app

COPY app/brokers brokers
RUN pip install --no-cache-dir -r brokers/requirements.txt

RUN rm brokers/requirements.txt

COPY app/core core
COPY app/api/v1/schemas api/v1/schemas
COPY app/models models
COPY app/services services
COPY app/celery_app celery_app
COPY app/providers providers

RUN pip uninstall win32-setctime colorama -y

CMD ["echo", "WARNING, RUN THIS DOCKERFILE IN DOCKER-COMPOSE"]
