"""added provider_id and failure_reason to notifications table

Revision ID: c7a42d86f371
Revises: 66ba0b6074ff
Create Date: 2026-07-10 16:57:10.545193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a42d86f371'
down_revision: Union[str, Sequence[str], None] = '66ba0b6074ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('provider_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('failure_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'failure_reason')
    op.drop_column('notifications', 'provider_id')
    # ### end Alembic commands ###
